image: node:latest

stages:
    - setup
    - test
    - deploy
    - deploy-beta
    - deploy-prod

variables:
    NODE_OPTIONS: --max-old-space-size=4096

before_script:
 - git config --global user.email $GIT_CI_EMAIL
 - git config --global user.name $GIT_CI_USERNAME

setup:
    stage: setup
    script:
        - npm install --no-audit
        - npx proton-pack config
    artifacts:
        paths:
            - node_modules/
            - src/app/config.js

lint:
    stage: test
    script:
        - npm run lint

i18n:
    stage: test
    script:
        - npm run i18n:validate
        - npm run i18n:validate:context

deploy:
    stage: deploy
    script:
        - npm i --no-audit
        - git clone "$(echo $CONFIG_GIT)" configApp
        - cp configApp/vpn-settings/appConfig.json .
        - cat configApp/.env configApp/vpn-settings/.env > .env
        - npm run deploy -- --branch=deploy-$BRANCH_DEPLOY --branch=deploy-$API_DEPLOY
    when: manual

deploy-beta:
    stage: deploy-beta
    script:
        - npm i --no-audit
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${CONFIG_GIT} ${CI_PROJECT_DIR}/configApp
        - cp ${CI_PROJECT_DIR}/configApp/vpn-settings/appConfig.json ${CI_PROJECT_DIR}/appConfig.json
        - cat ${CI_PROJECT_DIR}/configApp/.env ${CI_PROJECT_DIR}/configApp/vpn-settings/.env > ${CI_PROJECT_DIR}/.env
        - npm run deploy -- --branch=deploy-beta --api=beta --verbose --no-i18n --no-lint --force-fetch
    when: manual

deploy-prod:
    stage: deploy-prod
    script:
        - npm i --no-audit
        - git clone "$(echo $CONFIG_GIT)" configApp
        - cp configApp/vpn-settings/appConfig.json .
        - cat configApp/.env configApp/vpn-settings/.env > .env
        - npm run deploy -- --branch=deploy-prod --api=prod --no-i18n
    when: manual
